### ISSUE TITLE
CERT_UNTRUSTED error

### ISSUE THREAD

**Issue by sumproxy** [ewnd9/dictionary-cli#4]
I get the following error when using the latest version of dictionary-cli (1.1.2):

```
Unhandled rejection Error: CERT_UNTRUSTED
    at SecurePair.<anonymous> (tls.js:1346:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:959:10)
    at CleartextStream.read [as _read] (tls.js:463:15)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:219:10)
    at writeOrBuffer (_stream_writable.js:209:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:573:24)
    at flow (_stream_readable.js:582:7)
    at Socket.pipeOnReadable (_stream_readable.js:614:5)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
```

The reason seems to be it can't find the definition of the word. Use any like 'u'.

**Comment by ewnd9** [comment]
That's strange, it supposed to output "no translation". I guess it depends on language pair, which are yours?

**Comment by sumproxy** [comment]
I used from:en to:ru

**Comment by ewnd9** [comment]
After some googling I think you have something similar to nodejs/node-v0.x-archive#8894. As I remember from your previous issue you have node "0.8.9" (which is outdated), so try to upgrade at least to "0.10.x"

**Comment by sumproxy** [comment]
How can I get the _actual_ version of nodejs used by dict-cli?

```
node -v
```

tells me I have 0.10.9
I installed several package versions, so this could _potentially_ be the problem

**Comment by sumproxy** [comment]
BTW can you make saving search history optional? I can fix it locally, but if newer versions keep coming it gets bothersome..

**Comment by ewnd9** [comment]
Sure, I will make it optional. As for cert issue, I don't think I can do anything, it's more related to node itself than to the package

**Comment by sumproxy** [comment]
Is there a way to print to console the version of node used from the application, so I can make sure it's node version related?
Or better yet the node path used.

**Comment by ewnd9** [comment]
`/usr/bin/env node -v` (via https://github.com/ewnd9/dictionary-cli/blob/master/cli.js#L1)

**Comment by sumproxy** [comment]
Then I confirm that my node version is 0.10.9. Do you still think it's version related?

**Comment by sumproxy** [comment]
Strange, tried a few minutes ago and everything works fine

**Comment by ewnd9** [comment]
I've written test for "u" translation. It fails with strange errors on `v0.10.9` (https://travis-ci.org/ewnd9/dictionary-cli/jobs/79711677), but fines with latest `v0.10.40` (https://travis-ci.org/ewnd9/dictionary-cli/jobs/79711675)

**Comment by sumproxy** [comment]
I still get warnings during installation:

```
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.40","npm":"1.4.28"})
```

However, this time with 'u' as input I now get 'ед' instead of no translation, seems like yandex translate is kicking in instead of dictionary.

**Comment by ewnd9** [comment]
Warnings is just a warnings. And some of dependencies are really old, from node 0.8 times.
Kicking in yandex translate is expected behavior ;) Anything else I can help?

**Comment by sumproxy** [comment]
Yes, please, can I somehow turn off yandex translate? That might be a new issue though..

**Comment by ewnd9** [comment]
Sorry, but I don't see necessity in that. Dictionary output has different format, so you can always distinguish is it yandex dictionary or yandex translate.

**Comment by sumproxy** [comment]
I guess I'll have to figure out on my own
